/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface CreateEntryRequest {
  'weight' : number,
  'waterGlasses' : bigint,
  'date' : bigint,
  'calories' : bigint,
  'mood' : bigint,
  'steps' : bigint,
  'sleepHours' : number,
}
export type Date = bigint;
export interface Entry {
  'weight' : number,
  'waterGlasses' : bigint,
  'date' : bigint,
  'calories' : bigint,
  'mood' : bigint,
  'steps' : bigint,
  'sleepHours' : number,
}
export interface Goals {
  'targetSteps' : bigint,
  'targetCalories' : bigint,
  'targetSleepHours' : number,
  'targetWeight' : number,
  'targetWaterGlasses' : bigint,
}
export interface LogWorkoutRequest {
  'date' : bigint,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : number,
  'durationMinutes' : bigint,
  'notes' : string,
}
export interface QueryEntriesRequest {
  'endDate' : bigint,
  'startDate' : bigint,
}
export interface QueryWorkoutsRequest {
  'endDate' : bigint,
  'startDate' : bigint,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Workout {
  'id' : bigint,
  'date' : bigint,
  'name' : string,
  'reps' : bigint,
  'sets' : bigint,
  'weightKg' : number,
  'durationMinutes' : bigint,
  'notes' : string,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<[CreateEntryRequest], undefined>,
  'createGoals' : ActorMethod<[Goals], undefined>,
  'deleteWorkout' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntry' : ActorMethod<[Date], [] | [Entry]>,
  'getGoals' : ActorMethod<[], Goals>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkouts' : ActorMethod<[bigint], Array<Workout>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logWorkout' : ActorMethod<[LogWorkoutRequest], bigint>,
  'queryEntries' : ActorMethod<[QueryEntriesRequest], Array<Entry>>,
  'queryWorkouts' : ActorMethod<[QueryWorkoutsRequest], Array<Workout>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];