/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const CreateEntryRequest = IDL.Record({
  'weight' : IDL.Float64,
  'waterGlasses' : IDL.Nat,
  'date' : IDL.Nat,
  'calories' : IDL.Nat,
  'mood' : IDL.Nat,
  'steps' : IDL.Nat,
  'sleepHours' : IDL.Float64,
});
export const Goals = IDL.Record({
  'targetSteps' : IDL.Nat,
  'targetCalories' : IDL.Nat,
  'targetSleepHours' : IDL.Float64,
  'targetWeight' : IDL.Float64,
  'targetWaterGlasses' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Date = IDL.Nat;
export const Entry = IDL.Record({
  'weight' : IDL.Float64,
  'waterGlasses' : IDL.Nat,
  'date' : IDL.Nat,
  'calories' : IDL.Nat,
  'mood' : IDL.Nat,
  'steps' : IDL.Nat,
  'sleepHours' : IDL.Float64,
});
export const Workout = IDL.Record({
  'id' : IDL.Nat,
  'date' : IDL.Nat,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'weightKg' : IDL.Float64,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
});
export const LogWorkoutRequest = IDL.Record({
  'date' : IDL.Nat,
  'name' : IDL.Text,
  'reps' : IDL.Nat,
  'sets' : IDL.Nat,
  'weightKg' : IDL.Float64,
  'durationMinutes' : IDL.Nat,
  'notes' : IDL.Text,
});
export const QueryEntriesRequest = IDL.Record({
  'endDate' : IDL.Nat,
  'startDate' : IDL.Nat,
});
export const QueryWorkoutsRequest = IDL.Record({
  'endDate' : IDL.Nat,
  'startDate' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func([CreateEntryRequest], [], []),
  'createGoals' : IDL.Func([Goals], [], []),
  'deleteWorkout' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntry' : IDL.Func([Date], [IDL.Opt(Entry)], ['query']),
  'getGoals' : IDL.Func([], [Goals], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkouts' : IDL.Func([IDL.Nat], [IDL.Vec(Workout)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logWorkout' : IDL.Func([LogWorkoutRequest], [IDL.Nat], []),
  'queryEntries' : IDL.Func([QueryEntriesRequest], [IDL.Vec(Entry)], ['query']),
  'queryWorkouts' : IDL.Func(
      [QueryWorkoutsRequest],
      [IDL.Vec(Workout)],
      ['query'],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const CreateEntryRequest = IDL.Record({
    'weight' : IDL.Float64,
    'waterGlasses' : IDL.Nat,
    'date' : IDL.Nat,
    'calories' : IDL.Nat,
    'mood' : IDL.Nat,
    'steps' : IDL.Nat,
    'sleepHours' : IDL.Float64,
  });
  const Goals = IDL.Record({
    'targetSteps' : IDL.Nat,
    'targetCalories' : IDL.Nat,
    'targetSleepHours' : IDL.Float64,
    'targetWeight' : IDL.Float64,
    'targetWaterGlasses' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Date = IDL.Nat;
  const Entry = IDL.Record({
    'weight' : IDL.Float64,
    'waterGlasses' : IDL.Nat,
    'date' : IDL.Nat,
    'calories' : IDL.Nat,
    'mood' : IDL.Nat,
    'steps' : IDL.Nat,
    'sleepHours' : IDL.Float64,
  });
  const Workout = IDL.Record({
    'id' : IDL.Nat,
    'date' : IDL.Nat,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'weightKg' : IDL.Float64,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const LogWorkoutRequest = IDL.Record({
    'date' : IDL.Nat,
    'name' : IDL.Text,
    'reps' : IDL.Nat,
    'sets' : IDL.Nat,
    'weightKg' : IDL.Float64,
    'durationMinutes' : IDL.Nat,
    'notes' : IDL.Text,
  });
  const QueryEntriesRequest = IDL.Record({
    'endDate' : IDL.Nat,
    'startDate' : IDL.Nat,
  });
  const QueryWorkoutsRequest = IDL.Record({
    'endDate' : IDL.Nat,
    'startDate' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func([CreateEntryRequest], [], []),
    'createGoals' : IDL.Func([Goals], [], []),
    'deleteWorkout' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntry' : IDL.Func([Date], [IDL.Opt(Entry)], ['query']),
    'getGoals' : IDL.Func([], [Goals], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkouts' : IDL.Func([IDL.Nat], [IDL.Vec(Workout)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logWorkout' : IDL.Func([LogWorkoutRequest], [IDL.Nat], []),
    'queryEntries' : IDL.Func(
        [QueryEntriesRequest],
        [IDL.Vec(Entry)],
        ['query'],
      ),
    'queryWorkouts' : IDL.Func(
        [QueryWorkoutsRequest],
        [IDL.Vec(Workout)],
        ['query'],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };